version: '1'
networks:
  backend:
volumes:
  db1_data:
services:
  db-server:
    image: mysql:latest
    volumes:
      - db1_data:/var/lib/mysql
    restart: always
    networks:
      - backend
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
    container_name: db-server
  web:
    build: ./
    networks:
      - backend
    ports:
      - "5000:5000"
    container_name: web