version: '1'
services:
  db:
    image: mysql:latest
    networks:
      - backend
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
  web:
    build: ./
    networks:
      - backend
    ports:
      - "5000:5000"
networks:
    backend:
  
       
