version: '1'
networks:
  backend-network:
volumes:
  db1_data:
services:
  db-server:
    image: mysql:latest
    volumes:
      - db1_data:/var/lib/mysql
    restart: always
    networks:
      - backend-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      TEST: 'test'
    container_name: db-server
  web:
    build: ./
    networks:
      - backend-network
    restart: always
    ports:
      - "5000:5000"
    environment:
      db_host: db-server
      db_user: root
      db_password: 123456789
      db_name: expressjs
      TEST: 'test'
    container_name: web